/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlisinhvien_hibernate;

import dao.ClassRoomDAO;
import dao.StudentDAO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import pojos.ClassRoom;
import pojos.Student;

/**
 *
 * @author CPU12407-local
 */
public class addStudent extends javax.swing.JDialog {

    private String className = "", idCourse = "";

    /**
     * Creates new form add
     */
    public addStudent() {
        initComponents();
        init();
    }

    public addStudent(String _className) {
        this.className = _className;
        initComponents();
        init();
        String title = "Thêm Mới Học Sinh " + _className;
        this.jLabel5.setText(title);
    }

    public addStudent(String _className, String _idCourse) {
        this.className = _className;
        this.idCourse = _idCourse;
        initComponents();
        init();
        String title = "Thêm Mới Học Sinh " + _className + "-" + _idCourse;
        this.jLabel5.setText(title);
    }

    private void init() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();

        if (this.idCourse.equals("")) {
            model.addElement(this.className);
        } else {
            model.addElement(this.className + '-' + this.idCourse);
        }
        jcbClass.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgSex = new javax.swing.ButtonGroup();
        jtfMSSV = new javax.swing.JTextField();
        jtfName = new javax.swing.JTextField();
        jtfCMND = new javax.swing.JTextField();
        jrbSex1 = new javax.swing.JRadioButton();
        jrbSex2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbtAddStudent = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jcbClass = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm sinh viên");

        btgSex.add(jrbSex1);
        jrbSex1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbSex1.setText("Nam");
        jrbSex1.setToolTipText("");

        btgSex.add(jrbSex2);
        jrbSex2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbSex2.setText("Nữ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("MSSV:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Họ và tên:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Giới tính:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("CMND:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Thêm Mới Học Sinh");
        jLabel5.setToolTipText("");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jbtAddStudent.setText("Thêm");
        jbtAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddStudentActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Lớp:");

        jcbClass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbClass, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jtfMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jrbSex1)
                                .addGap(51, 51, 51)
                                .addComponent(jrbSex2)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtAddStudent)
                .addGap(24, 24, 24))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jcbClass, jtfCMND, jtfMSSV, jtfName});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, jLabel6});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jtfMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jrbSex1)
                    .addComponent(jrbSex2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jcbClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jcbClass, jtfCMND, jtfMSSV, jtfName});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel4, jLabel6});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddStudentActionPerformed
        String mssv = jtfMSSV.getText();
        String name = jtfName.getText();
        String cmnd = jtfCMND.getText();
        int sex = -1;

        if (jrbSex1.isSelected()) {
            sex = 0;
        }

        if (jrbSex2.isSelected()) {
            sex = 1;
        }

        boolean validate = this.validateForm();
        if (!validate) {
            String nameClass = String.valueOf(jcbClass.getItemAt(jcbClass.getSelectedIndex()));
            ClassRoom cr = ClassRoomDAO.getClassRoom(nameClass);
            Student sd = new Student(mssv, name, sex, cmnd, cr);

            boolean checkCreate = false;
            if (this.idCourse.equals("")) {
                checkCreate = StudentDAO.createStudent(sd);

            } else {
//                school.addStudentToClassCourse(this.className, this.idCourse, sd);
            }

            if (checkCreate) {
                JOptionPane.showMessageDialog(null, "Thêm học sinh thành công.");
                jtfMSSV.setText("");
                jtfName.setText("");
                jtfCMND.setText("");
            } else{
                JOptionPane.showMessageDialog(null, "Thêm học sinh không thành công.");
            } 

        }
    }//GEN-LAST:event_jbtAddStudentActionPerformed

    private boolean validateForm() {
        boolean validate = false;
        String mssv = jtfMSSV.getText();
        String name = jtfName.getText();
        String cmnd = jtfCMND.getText();
        StringBuilder msgErr = new StringBuilder();

        if (this.idCourse.equals("")) {
            Student student = StudentDAO.getStudent(mssv);
            if (student != null) {
                msgErr.append("MSSV đã tồn tại.");
                msgErr.append("\n");
            }
        } else {
//            ClassRoomCourse classRoomCourse = school.getClassRoomCourse(this.className, this.idCourse);
//            for (Student student : classRoomCourse.getListStudent()) {
//                if (student.checkMSSV(mssv)) {
//                    msgErr.append("MSSV đã tồn tại.");
//                    msgErr.append("\n");
//                }
//            }
        }

        if (mssv.equals("")) {
            validate = true;
            msgErr.append("MSSV không thể trống");
            msgErr.append("\n");
        }

        if (name.equals("")) {
            validate = true;
            msgErr.append("Tên không thể trống");
            msgErr.append("\n");
        }

        if (cmnd.equals("")) {
            validate = true;
            msgErr.append("CMND không thể trống");
            msgErr.append("\n");

        }

        if (jrbSex1.isSelected() == false && jrbSex2.isSelected() == false) {
            validate = true;
            msgErr.append("Vui lòng chọn giới tính");
            msgErr.append("\n");
        }

        if (validate == true) {
            JOptionPane.showMessageDialog(null, msgErr, "Error", JOptionPane.ERROR_MESSAGE);
        }

        return validate;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgSex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbtAddStudent;
    private javax.swing.JComboBox jcbClass;
    private javax.swing.JRadioButton jrbSex1;
    private javax.swing.JRadioButton jrbSex2;
    private javax.swing.JTextField jtfCMND;
    private javax.swing.JTextField jtfMSSV;
    private javax.swing.JTextField jtfName;
    // End of variables declaration//GEN-END:variables
}
