/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlisinhvien_hibernate;

import dao.CalenderCourseDAO;
import dao.ClassRoomCourseDAO;
import dao.ClassRoomDAO;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojos.CalenderCourse;
import pojos.ClassRoom;
import pojos.ClassRoomCourse;
import pojos.Student;

/**
 *
 * @author CPU12407-local
 */
public class manageCalenderCourse extends javax.swing.JFrame {

    private final int FILE_OPEN = 1;
    private final int FILE_SAVE = 2;
    private String className = "17HCB";
    private String[] columnNames = {
        "STT", "ID", "Mã môn", "Tên môn", "Phòng học", "Học Kỳ", "Năm"
    };

    manageStudent mStudent;

    /**
     * Creates new form manageCalenderCourse
     */
    public manageCalenderCourse() {
        initComponents();
        initLayout();
    }

    public manageCalenderCourse(String _className, manageStudent mStudent) {
        this.className = _className;
        this.mStudent = mStudent;
        initComponents();
        initLayout();
        this.mStudent.setVisible(false);
    }

    private void initLayout() {
        ArrayList<CalenderCourse> listCalenderCourse = ClassRoomDAO.getListCalenderCourse(className);
        if (listCalenderCourse.size() > 0) {
            int stt = 1;
            DefaultTableModel tableModel = new DefaultTableModel();
            DefaultComboBoxModel cbModel = new DefaultComboBoxModel();
            tableModel.setColumnIdentifiers(columnNames);
            for (CalenderCourse cCourse : listCalenderCourse) {
                String[] rows = new String[7];
                rows[0] = String.valueOf(stt);
                rows[1] = String.valueOf(cCourse.getId());
                rows[2] = cCourse.getMaCourse();
                rows[3] = cCourse.getNameCourse();
                rows[4] = cCourse.getLocation();
                rows[5] = cCourse.getHocKy();
                rows[6] = cCourse.getNamHoc();

                tableModel.addRow(rows);
                cbModel.addElement(cCourse.getMaCourse());
                stt++;
            }

            jtCalenderCourse.setModel(tableModel);
            jcbClassCourse.setModel(cbModel);
        } else {
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.setColumnIdentifiers(columnNames);
            jtCalenderCourse.setModel(tableModel);
            jcbClassCourse.setModel(new javax.swing.DefaultComboBoxModel(new String[]{}));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtCalenderCourse = new javax.swing.JTable();
        jbtImport = new javax.swing.JButton();
        jbtBack = new javax.swing.JButton();
        jcbClassCourse = new javax.swing.JComboBox();
        jbtnViewClassCourse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý lịch học");

        jtCalenderCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtCalenderCourse);

        jbtImport.setText("Import");
        jbtImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtImportActionPerformed(evt);
            }
        });

        jbtBack.setText("Back");
        jbtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBackActionPerformed(evt);
            }
        });

        jcbClassCourse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbtnViewClassCourse.setText("Class Course");
        jbtnViewClassCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnViewClassCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcbClassCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnViewClassCourse)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtImport)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jbtImport))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbClassCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnViewClassCourse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtImportActionPerformed
        operateFile("Choose file import", FILE_OPEN);
    }//GEN-LAST:event_jbtImportActionPerformed

    private void jbtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBackActionPerformed
        this.mStudent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtBackActionPerformed

    private void jbtnViewClassCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnViewClassCourseActionPerformed
        String idCourse = String.valueOf(jcbClassCourse.getItemAt(jcbClassCourse.getSelectedIndex()));
        if (!idCourse.equals("null")) {
            manageClassRoomCourse mClassRoomCourse = new manageClassRoomCourse(this, this.className, idCourse);
            mClassRoomCourse.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Chưa có danh sách lịch học.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbtnViewClassCourseActionPerformed

    private void operateFile(String title, int type) {
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle(title);
        int choose = -1;
        switch (type) {
            case FILE_OPEN:
                choose = chooser.showOpenDialog(null);
                break;
        }

        if (choose == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            switch (type) {
                case FILE_OPEN:
                    readFile(file);
                    break;
            }
        }
    }

    private void readFile(File file) {
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            String line;
            // Lấy tên lớp
            line = br.readLine();
            String[] _className = line.split(",");
            String maClass = _className[0].replaceAll("﻿", "");
            String hocKy = _className[1];
            String namHoc = _className[2];
            
            System.out.println(_className[0]);
            System.out.println(_className[1]);
            System.out.println(_className[2]);

            while ((line = br.readLine()) != null) {
                String[] _cCourse = line.split(",");

                CalenderCourse calenderCourse = new CalenderCourse(_cCourse[0], _cCourse[1], maClass, _cCourse[2], hocKy, namHoc);

                boolean checkCreacte = CalenderCourseDAO.createCalenderCourse(calenderCourse);
                
                // Thêm danh sách sv của lớp vào bảng ClassRoomCourse
                if(checkCreacte) {
                    CalenderCourse cCourse = CalenderCourseDAO.getCalenderCourse(maClass, _cCourse[0]);
                    ClassRoom cr = ClassRoomDAO.getClassRoom(maClass);
                    Set<Student> listStudent = cr.getListStudent();
                    for(Student sd : listStudent) {
                        ClassRoomCourse _crc = new ClassRoomCourse(maClass, cCourse.getId().toString(), sd.getMaStudent());
                        ClassRoomCourseDAO.addStudentInCourse(_crc);
                    }
                }
            }
            br.close();

            initLayout();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error to open file: " + e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageCalenderCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageCalenderCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageCalenderCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageCalenderCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageCalenderCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtBack;
    private javax.swing.JButton jbtImport;
    private javax.swing.JButton jbtnViewClassCourse;
    private javax.swing.JComboBox jcbClassCourse;
    private javax.swing.JTable jtCalenderCourse;
    // End of variables declaration//GEN-END:variables
}
