/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlisinhvien_hibernate;

import dao.ReexamineDAO;
import dao.TableReexamineDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojos.Reexamine;
import pojos.TableReexamine;

/**
 *
 * @author DoDuyPhuong
 */
public class manageReexamine extends javax.swing.JFrame {

    /**
     * Creates new form manageReexamine
     */
    private manageTableReexamine mTableReexamine;
    private int idTableReexamine;
    private final String[] columnNames = {
        "STT", "ID", "MSSV", "Họ Tên", "Môn Học", "Cột Điểm", "Điểm Đề Nghị", "Mô Tả", "Trạng Thái"
    };

    public manageReexamine() {
        this.setResizable(false);
        initComponents();
        initLayout();
    }

    public manageReexamine(manageTableReexamine mTableReexamine, int idTableReexamine) {
        this.setResizable(false);
        this.mTableReexamine = mTableReexamine;
        this.idTableReexamine = idTableReexamine;
        this.mTableReexamine.setVisible(false);
        initComponents();
        initLayout();
    }

    private void initLayout() {
        TableReexamine tReexamine = TableReexamineDAO.checkTableReeaxamineExist(idTableReexamine);
        if (tReexamine != null) {
            String t = tReexamine.getNamHoc() + "-" + tReexamine.getHocKy();
            this.jHeader.setText(t);
        }
        List<Reexamine> listReexamine = ReexamineDAO.getListReexamine(idTableReexamine);
        if (listReexamine.size() > 0) {
            int stt = 1;
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.setColumnIdentifiers(columnNames);
            // "STT", "ID", "MSSV", "Họ Tên", "Môn Học", "Cột Điểm", "Điểm Đề Nghị", "Mô Tả", "Trạng Thái"
            for (Reexamine re : listReexamine) {
                String[] rows = new String[9];
                rows[0] = String.valueOf(stt);
                rows[1] = String.valueOf(re.getId());
                rows[2] = re.getMssv();
                rows[3] = re.getName();
                rows[4] = re.getCourse();
                rows[5] = re.getRowScore();
                rows[6] = re.getSuggestScore().toString();
                rows[7] = re.getDescription();
                rows[8] = re.getStatus();

                tableModel.addRow(rows);
                stt++;
            }

            jTableReexamine.setModel(tableModel);
        } else {
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.setColumnIdentifiers(columnNames);
            jTableReexamine.setModel(tableModel);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReexamine = new javax.swing.JTable();
        jHeader = new javax.swing.JLabel();
        jbtnBack = new javax.swing.JButton();
        jView = new javax.swing.JButton();
        jPannelViewReexamine = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtMSSV = new javax.swing.JTextField();
        jtxtName = new javax.swing.JTextField();
        jtxtCourse = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtRowScore = new javax.swing.JTextField();
        jtxtSuggestScore = new javax.swing.JTextField();
        jcbStatus = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jDescription = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jbtnUpdate = new javax.swing.JButton();
        jtxtID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableReexamine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableReexamine);

        jHeader.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jHeader.setText("Yêu Cầu Phúc Khảo");

        jbtnBack.setText("Back");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        jView.setText("View");
        jView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jViewActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("MSSV:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Họ tên:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Môn học:");

        jtxtMSSV.setEnabled(false);
        jtxtMSSV.setMinimumSize(new java.awt.Dimension(6, 24));

        jtxtName.setEnabled(false);

        jtxtCourse.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Cột điểm:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Điểm đề nghị:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Trạng thái:");

        jtxtRowScore.setEnabled(false);
        jtxtRowScore.setMinimumSize(new java.awt.Dimension(6, 24));

        jtxtSuggestScore.setEnabled(false);

        jcbStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Đã cập nhật", "Không cập nhật", "Chưa Xem" }));

        jDescription.setColumns(20);
        jDescription.setRows(5);
        jDescription.setEnabled(false);
        jScrollPane2.setViewportView(jDescription);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Lý do:");

        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });

        jtxtID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtID.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("ID:");

        javax.swing.GroupLayout jPannelViewReexamineLayout = new javax.swing.GroupLayout(jPannelViewReexamine);
        jPannelViewReexamine.setLayout(jPannelViewReexamineLayout);
        jPannelViewReexamineLayout.setHorizontalGroup(
            jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPannelViewReexamineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtID)
                    .addComponent(jtxtName)
                    .addComponent(jtxtCourse)
                    .addComponent(jtxtMSSV, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPannelViewReexamineLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jtxtRowScore, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                    .addGroup(jPannelViewReexamineLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtSuggestScore))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnUpdate)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18))
        );

        jPannelViewReexamineLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtxtCourse, jtxtMSSV, jtxtName});

        jPannelViewReexamineLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jcbStatus, jtxtRowScore, jtxtSuggestScore});

        jPannelViewReexamineLayout.setVerticalGroup(
            jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPannelViewReexamineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPannelViewReexamineLayout.createSequentialGroup()
                        .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtRowScore, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jtxtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jtxtSuggestScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jtxtCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPannelViewReexamineLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnUpdate)
                    .addComponent(jtxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPannelViewReexamineLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtxtCourse, jtxtMSSV, jtxtName, jtxtRowScore, jtxtSuggestScore});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jPannelViewReexamine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jView))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnBack)
                        .addGap(181, 181, 181)
                        .addComponent(jHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                        .addGap(212, 212, 212)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBack))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPannelViewReexamine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        // TODO add your handling code here:
        this.mTableReexamine.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jViewActionPerformed
        // TODO add your handling code here:
        int selectRow = jTableReexamine.getSelectedRow();
        if (selectRow >= 0) {
            //"STT", "ID", "MSSV", "Họ Tên", "Môn Học", "Cột Điểm", "Điểm Đề Nghị", "Mô Tả", "Trạng Thái"
            String id = (String) jTableReexamine.getValueAt(selectRow, 1);
            this.jtxtID.setText(id);
            
            String mssv = (String) jTableReexamine.getValueAt(selectRow, 2);
            this.jtxtMSSV.setText(mssv);
            
            String name = (String) jTableReexamine.getValueAt(selectRow, 3);
            this.jtxtName.setText(name);
            
            String course = (String) jTableReexamine.getValueAt(selectRow, 4);
            this.jtxtCourse.setText(course);
            
            String rowScore = (String) jTableReexamine.getValueAt(selectRow, 5);
            this.jtxtRowScore.setText(rowScore);
            
            String suggetScore = (String) jTableReexamine.getValueAt(selectRow, 6);
            this.jtxtSuggestScore.setText(suggetScore);
            
            String description = (String) jTableReexamine.getValueAt(selectRow, 7);
            this.jDescription.setText(description);
            
            String status = (String) jTableReexamine.getValueAt(selectRow, 8);
            this.jcbStatus.setSelectedItem(status);
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn dòng để thực hiện", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jViewActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        // TODO add your handling code here:
        int id = Integer.valueOf(this.jtxtID.getText());
        Reexamine re = ReexamineDAO.getReexamine(id);
        if(re != null) {
            String status = (String) jcbStatus.getItemAt(jcbStatus.getSelectedIndex());
            re.setStatus(status);
            boolean checkUpdate = ReexamineDAO.updateReexamine(re);
            if(checkUpdate) {
                JOptionPane.showMessageDialog(null, "Cập nhật thành công.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Xảy ra lỗi cập nhật.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }
            initLayout();
        } else {
            JOptionPane.showMessageDialog(null, "Xảy ra lỗi cập nhật.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            initLayout();
        }
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageReexamine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageReexamine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageReexamine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageReexamine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageReexamine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jDescription;
    private javax.swing.JLabel jHeader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPannelViewReexamine;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableReexamine;
    private javax.swing.JButton jView;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JComboBox jcbStatus;
    private javax.swing.JTextField jtxtCourse;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JTextField jtxtMSSV;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtRowScore;
    private javax.swing.JTextField jtxtSuggestScore;
    // End of variables declaration//GEN-END:variables
}
