package pojos;
// Generated Aug 6, 2019 3:39:38 PM by Hibernate Tools 4.3.1



/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private String userName;
     private String passwd;
     private String maClass;
     private Integer role;

    public Account() {
    }

	
    public Account(String userName, String passwd) {
        this.userName = userName;
        this.passwd = passwd;
    }
    public Account(String userName, String passwd, String maClass, Integer role) {
       this.userName = userName;
       this.passwd = passwd;
       this.maClass = maClass;
       this.role = role;
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPasswd() {
        return this.passwd;
    }
    
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
    public String getMaClass() {
        return this.maClass;
    }
    
    public void setMaClass(String maClass) {
        this.maClass = maClass;
    }
    public Integer getRole() {
        return this.role;
    }
    
    public void setRole(Integer role) {
        this.role = role;
    }




}


