package pojos;
// Generated Aug 7, 2019 9:45:00 AM by Hibernate Tools 4.3.1



/**
 * CalenderCourse generated by hbm2java
 */
public class CalenderCourse  implements java.io.Serializable {


     private Integer id;
     private String maCourse;
     private String maClass;
     private String location;

    public CalenderCourse() {
    }

    public CalenderCourse(String maCourse, String maClass, String location) {
       this.maCourse = maCourse;
       this.maClass = maClass;
       this.location = location;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMaCourse() {
        return this.maCourse;
    }
    
    public void setMaCourse(String maCourse) {
        this.maCourse = maCourse;
    }
    public String getMaClass() {
        return this.maClass;
    }
    
    public void setMaClass(String maClass) {
        this.maClass = maClass;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }




}


