package pojos;
// Generated Aug 6, 2019 3:39:38 PM by Hibernate Tools 4.3.1



/**
 * Classroom generated by hbm2java
 */
public class Classroom  implements java.io.Serializable {


     private String maClass;

    public Classroom() {
    }

    public Classroom(String maClass) {
       this.maClass = maClass;
    }
   
    public String getMaClass() {
        return this.maClass;
    }
    
    public void setMaClass(String maClass) {
        this.maClass = maClass;
    }




}


