package pojos;
// Generated Aug 7, 2019 9:45:00 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;


/**
 * ClassRoom generated by hbm2java
 */
public class ClassRoom implements java.io.Serializable {

    private String maClass;
    private Set<Student> listStudent = new HashSet<Student>(0);
    
    public ClassRoom() {
    }

    public ClassRoom(String maClass) {
        this.maClass = maClass;
    }

    public String getMaClass() {
        return this.maClass;
    }

    public void setMaClass(String maClass) {
        this.maClass = maClass;
    }

    public Set<Student> getListStudent() {
        return listStudent;
    }

    public void setListStudent(Set<Student> listStudent) {
        this.listStudent = listStudent;
    }

}
