package pojos;
// Generated Aug 7, 2019 9:45:00 AM by Hibernate Tools 4.3.1



/**
 * ClassRoomCourse generated by hbm2java
 */
public class ClassRoomCourse  implements java.io.Serializable {


     private Integer id;
     private String maClass;
     private String maCourse;
     private String maStudent;

    public ClassRoomCourse() {
    }

    public ClassRoomCourse(String maClass, String maCourse, String maStudent) {
       this.maClass = maClass;
       this.maCourse = maCourse;
       this.maStudent = maStudent;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMaClass() {
        return this.maClass;
    }
    
    public void setMaClass(String maClass) {
        this.maClass = maClass;
    }
    public String getMaCourse() {
        return this.maCourse;
    }
    
    public void setMaCourse(String maCourse) {
        this.maCourse = maCourse;
    }
    public String getMaStudent() {
        return this.maStudent;
    }
    
    public void setMaStudent(String maStudent) {
        this.maStudent = maStudent;
    }




}


