package pojos;
// Generated Aug 12, 2019 10:15:22 AM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;




/**
 * ClassRoom generated by hbm2java
 */
public class ClassRoom  implements java.io.Serializable {
    private String maClass;
    private Set<Student> listStudent = new HashSet<Student>(0);
    private ArrayList<CalenderCourse> listCourse = new ArrayList<CalenderCourse>();
    public ClassRoom() {
    }

    public ClassRoom(String maClass) {
       this.maClass = maClass;
    }
   
    public String getMaClass() {
        return this.maClass;
    }
    
    public void setMaClass(String maClass) {
        this.maClass = maClass;
    }

    public Set<Student> getListStudent() {
        return listStudent;
    }

    public void setListStudent(Set<Student> listStudent) {
        this.listStudent = listStudent;
    }

    public ArrayList<CalenderCourse> getListCourse() {
        return listCourse;
    }

    public void setListCourse(ArrayList<CalenderCourse> listCourse) {
        this.listCourse = listCourse;
    }
    
}


