package pojos;
// Generated Aug 7, 2019 9:45:00 AM by Hibernate Tools 4.3.1



/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private String maCourse;
     private String nameCourse;

    public Course() {
    }

    public Course(String maCourse, String nameCourse) {
       this.maCourse = maCourse;
       this.nameCourse = nameCourse;
    }
   
    public String getMaCourse() {
        return this.maCourse;
    }
    
    public void setMaCourse(String maCourse) {
        this.maCourse = maCourse;
    }
    public String getNameCourse() {
        return this.nameCourse;
    }
    
    public void setNameCourse(String nameCourse) {
        this.nameCourse = nameCourse;
    }




}


