package pojos;
// Generated Aug 12, 2019 10:15:22 AM by Hibernate Tools 4.3.1



/**
 * Reexamine generated by hbm2java
 */
public class Reexamine  implements java.io.Serializable {


     private int id;
     private String mssv;
     private String name;
     private String course;
     private String rowScore;
     private Double suggestScore;
     private String description;
     private String status;

    public Reexamine() {
    }

	
    public Reexamine(int id, String mssv) {
        this.id = id;
        this.mssv = mssv;
    }
    public Reexamine(int id, String mssv, String name, String course, String rowScore, Double suggestScore, String description, String status) {
       this.id = id;
       this.mssv = mssv;
       this.name = name;
       this.course = course;
       this.rowScore = rowScore;
       this.suggestScore = suggestScore;
       this.description = description;
       this.status = status;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCourse() {
        return this.course;
    }
    
    public void setCourse(String course) {
        this.course = course;
    }
    public String getRowScore() {
        return this.rowScore;
    }
    
    public void setRowScore(String rowScore) {
        this.rowScore = rowScore;
    }
    public Double getSuggestScore() {
        return this.suggestScore;
    }
    
    public void setSuggestScore(Double suggestScore) {
        this.suggestScore = suggestScore;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


