package pojos;
// Generated Aug 12, 2019 10:15:22 AM by Hibernate Tools 4.3.1



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private String maStudent;
     private String nameStudent;
     private int sex;
     private String cmnd;
     private ClassRoom classRoom;
     
    public Student() {
    }
	
    public Student(String maStudent, String nameStudent, int sex, String cmnd) {
        this.maStudent = maStudent;
        this.nameStudent = nameStudent;
        this.sex = sex;
        this.cmnd = cmnd;
    }
    
    public Student(String maStudent, String nameStudent, String cmnd, ClassRoom classRoom) {
        this.maStudent = maStudent;
        this.nameStudent = nameStudent;
        this.cmnd = cmnd;
        this.classRoom = classRoom;
    }
    
    public Student(String maStudent, String nameStudent, int sex, String cmnd, ClassRoom classRoom) {
        this.maStudent = maStudent;
        this.nameStudent = nameStudent;
        this.sex = sex;
        this.cmnd = cmnd;
        this.classRoom = classRoom;
    }
   
    public String getMaStudent() {
        return this.maStudent;
    }
    
    public void setMaStudent(String maStudent) {
        this.maStudent = maStudent;
    }
    public String getNameStudent() {
        return this.nameStudent;
    }
    
    public void setNameStudent(String nameStudent) {
        this.nameStudent = nameStudent;
    }
    public int getSex() {
        return this.sex;
    }
    
    public void setSex(int sex) {
        this.sex = sex;
    }
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }

    public ClassRoom getClassRoom() {
        return classRoom;
    }

    public void setClassRoom(ClassRoom classRoom) {
        this.classRoom = classRoom;
    }

}


