package pojos;
// Generated Aug 7, 2019 9:45:00 AM by Hibernate Tools 4.3.1



/**
 * TableScore generated by hbm2java
 */
public class TableScore  implements java.io.Serializable {


     private Integer id;
     private String maClass;
     private String maCourse;
     private String maStudent;
     private Double scoreMiddleTest;
     private Double scoreFinalTest;
     private Double scoreDifferent;
     private Double finalScore;

    public TableScore() {
    }

	
    public TableScore(String maClass, String maCourse, String maStudent) {
        this.maClass = maClass;
        this.maCourse = maCourse;
        this.maStudent = maStudent;
    }
    public TableScore(String maClass, String maCourse, String maStudent, Double scoreMiddleTest, Double scoreFinalTest, Double scoreDifferent, Double finalScore) {
       this.maClass = maClass;
       this.maCourse = maCourse;
       this.maStudent = maStudent;
       this.scoreMiddleTest = scoreMiddleTest;
       this.scoreFinalTest = scoreFinalTest;
       this.scoreDifferent = scoreDifferent;
       this.finalScore = finalScore;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMaClass() {
        return this.maClass;
    }
    
    public void setMaClass(String maClass) {
        this.maClass = maClass;
    }
    public String getMaCourse() {
        return this.maCourse;
    }
    
    public void setMaCourse(String maCourse) {
        this.maCourse = maCourse;
    }
    public String getMaStudent() {
        return this.maStudent;
    }
    
    public void setMaStudent(String maStudent) {
        this.maStudent = maStudent;
    }
    public Double getScoreMiddleTest() {
        return this.scoreMiddleTest;
    }
    
    public void setScoreMiddleTest(Double scoreMiddleTest) {
        this.scoreMiddleTest = scoreMiddleTest;
    }
    public Double getScoreFinalTest() {
        return this.scoreFinalTest;
    }
    
    public void setScoreFinalTest(Double scoreFinalTest) {
        this.scoreFinalTest = scoreFinalTest;
    }
    public Double getScoreDifferent() {
        return this.scoreDifferent;
    }
    
    public void setScoreDifferent(Double scoreDifferent) {
        this.scoreDifferent = scoreDifferent;
    }
    public Double getFinalScore() {
        return this.finalScore;
    }
    
    public void setFinalScore(Double finalScore) {
        this.finalScore = finalScore;
    }




}


