package pojos;
// Generated Aug 12, 2019 10:15:22 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * TableReexamine generated by hbm2java
 */
public class TableReexamine implements java.io.Serializable {

    private Integer id;
    private String hocKy;
    private String namHoc;
    private Integer status;
    private Date startDate;
    private Date endDate;
    private String created;
    private String modified;

    public TableReexamine() {
    }

    public TableReexamine(Date startDate, Date endDate, String created, String modified) {
        this.startDate = startDate;
        this.endDate = endDate;
        this.created = created;
        this.modified = modified;
    }

    public TableReexamine(String hocKy, Integer status, String namHoc, Date startDate, Date endDate, String created, String modified) {
        this.hocKy = hocKy;
        this.namHoc = namHoc;
        this.status = status;
        this.startDate = startDate;
        this.endDate = endDate;
        this.created = created;
        this.modified = modified;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public String getCreated() {
        return this.created;
    }

    public void setCreated(String created) {
        this.created = created;
    }

    public String getModified() {
        return this.modified;
    }

    public void setModified(String modified) {
        this.modified = modified;
    }

    public String getHocKy() {
        return hocKy;
    }

    public void setHocKy(String hocKy) {
        this.hocKy = hocKy;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getNamHoc() {
        return namHoc;
    }

    public void setNamHoc(String namHoc) {
        this.namHoc = namHoc;
    }

}
