package pojos;
// Generated Aug 12, 2019 10:15:22 AM by Hibernate Tools 4.3.1



/**
 * TableScore generated by hbm2java
 */
public class TableScore  implements java.io.Serializable {


     private Integer id;
     private Integer idCalenderCourse;
     private String maStudent;
     private Double scoreMiddleTest;
     private Double scoreFinalTest;
     private Double scoreDifferent;
     private Double finalScore;

    public TableScore() {
    }

	
    public TableScore(Integer idCalenderCourse, String maStudent) {
        this.idCalenderCourse = idCalenderCourse;
        this.maStudent = maStudent;
    }
    public TableScore(Integer idCalenderCourse, String maStudent, Double scoreMiddleTest, Double scoreFinalTest, Double scoreDifferent, Double finalScore) {
       this.idCalenderCourse = idCalenderCourse;
       this.maStudent = maStudent;
       this.scoreMiddleTest = scoreMiddleTest;
       this.scoreFinalTest = scoreFinalTest;
       this.scoreDifferent = scoreDifferent;
       this.finalScore = finalScore;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getIdCalenderCourse() {
        return idCalenderCourse;
    }

    public void setIdCalenderCourse(Integer idCalenderCourse) {
        this.idCalenderCourse = idCalenderCourse;
    }
    
    public String getMaStudent() {
        return this.maStudent;
    }
    
    public void setMaStudent(String maStudent) {
        this.maStudent = maStudent;
    }
    public Double getScoreMiddleTest() {
        return this.scoreMiddleTest;
    }
    
    public void setScoreMiddleTest(Double scoreMiddleTest) {
        this.scoreMiddleTest = scoreMiddleTest;
    }
    public Double getScoreFinalTest() {
        return this.scoreFinalTest;
    }
    
    public void setScoreFinalTest(Double scoreFinalTest) {
        this.scoreFinalTest = scoreFinalTest;
    }
    public Double getScoreDifferent() {
        return this.scoreDifferent;
    }
    
    public void setScoreDifferent(Double scoreDifferent) {
        this.scoreDifferent = scoreDifferent;
    }
    public Double getFinalScore() {
        return this.finalScore;
    }
    
    public void setFinalScore(Double finalScore) {
        this.finalScore = finalScore;
    }




}


